worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: debug

is_testing: true

server-port: 8080
server-grpc-port: 8081

hello-endpoint: '[::1]:8081'

# kiddy_line_processor_db-1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/kiddy_line_processor_db_1'
